lines: 90
statements: 90
functions: 85
branches: 60
include:
  - src
extension:
  - ".ts"
require: ts-node/register
sourceMap: true
instrument: true
cache: true
check-coverage: true
all: true
report-dir: "./coverage"
reporter:
  - lcov
  - text
  - json
exclude:
  - src/c.ts
  - src/error.ts
