lines: 99
statements: 99
functions: 99
branches: 98
include:
  - src
extension:
  - ".ts"
require: ts-node/register
sourceMap: true
instrument: true
cache: true
check-coverage: true
all: true
report-dir: "./coverage"
reporter:
  - lcov
  - text
  - json
